model:
  base_learning_rate: 3.0e-06
  target: ldm.models.diffusion.cfm1_audio.CFM
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    mel_dim: 20
    channels: 0
    cond_stage_trainable: True
    conditioning_key: hybrid
    monitor: val/loss_simple_ema
    scale_by_std: true
    use_ema: false
    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps:
        - 10000
        cycle_lengths:
        - 10000000000000
        f_start:
        - 1.0e-06
        f_max:
        - 1.0
        f_min:
        - 1.0
    unet_config:
      target: ldm.modules.diffusionmodules.tcsinger2.TCSinger2
      params:
        in_channels: 20
        ori_dim: 1024
        context_dim: 768
        hidden_size: 768
        num_heads: 8
        depth: 4
        max_len: 3760
        num_experts: 4

    first_stage_config:
      target: ldm.models.autoencoder1d.AutoencoderKL
      params:
        embed_dim: 20
        monitor: val/rec_loss
        ckpt_path: logs/2025-07-08T23-39-28_ae_singing/checkpoints/last.ckpt
        ddconfig:
          double_z: true
          in_channels: 80
          out_ch: 80
          z_channels: 20
          kernel_size: 5
          ch: 384
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_layers:
          - 2
          down_layers:
          - 0
          - 1
          # - 2
          dropout: 0.0
          hidden_size: 256
          dur_predictor_kernel: 3
          dur_predictor_layers: 2
          predictor_dropout: 0.5
          enc_layers: 4
          enc_ffn_kernel_size: 9
          enc_prenet: true
          enc_pre_ln: true
          num_heads: 2
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenTextVocalEmbedder
      params:
        version: useful_ckpts/flan-t5-large
        max_length: 80

lightning:
  callbacks:
    image_logger:
      target: main.AudioLogger
      params:
        sample_rate: 48000
        for_specs: true
        increase_log_steps: false
        batch_frequency: 5000
        max_images: 8
        melvmin: -5
        melvmax: 1.5
        vocoder_cfg:
          target: vocoder.hifigan.hifigan_nsf.HifiGAN_NSF
          params:
            vocoder_ckpt: useful_ckpts/hifigan
            use_nsf: true
  trainer:
    benchmark: True
    gradient_clip_val: 1.0
    replace_sampler_ddp: false
  modelcheckpoint:
    params:
      monitor: epoch
      mode: max
      save_top_k: 10
      every_n_epochs: 10

data:
  target: main.SpectrogramDataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 4
    main_spec_dir_path: 'data/sing'
    other_spec_dir_path: ''
    mel_num: 80
    drop: 0.1
    spec_crop_len: 3760
    train:
      target: ldm.data.tcsinger2_dataset.JoinSpecsTrain
      params:
        specs_dataset_cfg:
    validation:
      target: ldm.data.tcsinger2_dataset.JoinSpecsValidation
      params:
        specs_dataset_cfg:

test_dataset:
  target: ldm.data.tsvdataset.TSVDatasetStruct
  params:
    tsv_path: audiocaps_test_16000_struct2.tsv
    spec_crop_len: 3760
